# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e79440515bdbfbf2568e40b1c9ab72abb2e316216cbf9b082d3f12d80ac0e4d8355a5103eff6f99105639e2f0cd39761f8c1a8949e548ac1c2c292ac4c839e0a

test:
  secret_key_base: 8f56513f11bcc537ec3148a447d93b0175b05fc052a4cd9c07fe39f8bcabca3b2f23e3cb498b4b439a4d177752b8989f3b9056a1462019c02b9f5f08de58fef7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
